export const dummyData = [
    {
      "asset_id": 1,
      "asset_type": "Elevator",
      "floor": 7,
      "room": 103,
      "installation_date": "1/6/2020",
      "manufacturer": "Manufacturer_4",
      "operational_time": 39313,
      "work_orders": 0,
      "repairs": 1,
      "last_serviced_date": "6/19/2023"
    },
    {
      "asset_id": 2,
      "asset_type": "Plumbing System",
      "floor": 6,
      "room": 109,
      "installation_date": "6/11/2022",
      "manufacturer": "Manufacturer_2",
      "operational_time": 20012,
      "work_orders": 0,
      "repairs": 1,
      "last_serviced_date": "1/6/2023"
    },
    {
      "asset_id": 3,
      "asset_type": "Fire Alarm",
      "floor": 3,
      "room": 104,
      "installation_date": "7/24/2019",
      "manufacturer": "Manufacturer_4",
      "operational_time": 21546,
      "work_orders": 10,
      "repairs": 5,
      "last_serviced_date": "9/24/2022"
    },
    {
      "asset_id": 4,
      "asset_type": "Elevator",
      "floor": 1,
      "room": 105,
      "installation_date": "1/4/2021",
      "manufacturer": "Manufacturer_4",
      "operational_time": 47038,
      "work_orders": 1,
      "repairs": 1,
      "last_serviced_date": "5/23/2023"
    },
    {
      "asset_id": 5,
      "asset_type": "Plumbing System",
      "floor": 2,
      "room": 104,
      "installation_date": "11/28/2022",
      "manufacturer": "Manufacturer_1",
      "operational_time": 20022,
      "work_orders": 10,
      "repairs": 3,
      "last_serviced_date": "1/29/2023"
    },
    {
      "asset_id": 6,
      "asset_type": "Fire Alarm",
      "floor": 2,
      "room": 103,
      "installation_date": "7/29/2021",
      "manufacturer": "Manufacturer_3",
      "operational_time": 1602,
      "work_orders": 9,
      "repairs": 4,
      "last_serviced_date": "10/3/2022"
    },
    {
      "asset_id": 7,
      "asset_type": "Fire Alarm",
      "floor": 6,
      "room": 108,
      "installation_date": "8/23/2020",
      "manufacturer": "Manufacturer_2",
      "operational_time": 15650,
      "work_orders": 2,
      "repairs": 3,
      "last_serviced_date": "1/13/2023"
    },
    {
      "asset_id": 8,
      "asset_type": "HVAC",
      "floor": 2,
      "room": 106,
      "installation_date": "6/3/2021",
      "manufacturer": "Manufacturer_2",
      "operational_time": 33932,
      "work_orders": 1,
      "repairs": 4,
      "last_serviced_date": "8/9/2023"
    },
    {
      "asset_id": 9,
      "asset_type": "Fire Alarm",
      "floor": 6,
      "room": 108,
      "installation_date": "7/30/2023",
      "manufacturer": "Manufacturer_5",
      "operational_time": 24332,
      "work_orders": 5,
      "repairs": 4,
      "last_serviced_date": "2/13/2023"
    },
    {
      "asset_id": 10,
      "asset_type": "Elevator",
      "floor": 7,
      "room": 101,
      "installation_date": "7/24/2019",
      "manufacturer": "Manufacturer_4",
      "operational_time": 18722,
      "work_orders": 10,
      "repairs": 2,
      "last_serviced_date": "5/29/2023"
    },
    {
      "asset_id": 11,
      "asset_type": "HVAC",
      "floor": 3,
      "room": 103,
      "installation_date": "6/19/2022",
      "manufacturer": "Manufacturer_2",
      "operational_time": null,
      "work_orders": 6,
      "repairs": 1,
      "last_serviced_date": "6/19/2023"
    },
    {
      "asset_id": 12,
      "asset_type": "Electrical Panel",
      "floor": 10,
      "room": 105,
      "installation_date": "5/14/2022",
      "manufacturer": "Manufacturer_2",
      "operational_time": 46525,
      "work_orders": 8,
      "repairs": 1,
      "last_serviced_date": "11/25/2022"
    },
    {
      "asset_id": 13,
      "asset_type": "Fire Alarm",
      "floor": 6,
      "room": 106,
      "installation_date": "4/13/2019",
      "manufacturer": "Manufacturer_2",
      "operational_time": 43437,
      "work_orders": 7,
      "repairs": 2,
      "last_serviced_date": "11/30/2022"
    },
    {
      "asset_id": 14,
      "asset_type": "Elevator",
      "floor": 1,
      "room": 103,
      "installation_date": "3/11/2023",
      "manufacturer": "Manufacturer_4",
      "operational_time": 18211,
      "work_orders": 0,
      "repairs": 4,
      "last_serviced_date": "9/4/2023"
    },
    {
      "asset_id": 15,
      "asset_type": "Fire Alarm",
      "floor": 5,
      "room": 107,
      "installation_date": "11/30/2019",
      "manufacturer": "Manufacturer_5",
      "operational_time": 29177,
      "work_orders": 8,
      "repairs": 4,
      "last_serviced_date": "8/22/2023"
    },
    {
      "asset_id": 16,
      "asset_type": "HVAC",
      "floor": 7,
      "room": 103,
      "installation_date": "12/24/2019",
      "manufacturer": "Manufacturer_1",
      "operational_time": 12953,
      "work_orders": 2,
      "repairs": 4,
      "last_serviced_date": "11/17/2022"
    },
    {
      "asset_id": 17,
      "asset_type": "Electrical Panel",
      "floor": 2,
      "room": 101,
      "installation_date": "12/17/2018",
      "manufacturer": "Manufacturer_5",
      "operational_time": 48382,
      "work_orders": 9,
      "repairs": 5,
      "last_serviced_date": "1/13/2023"
    },
    {
      "asset_id": 18,
      "asset_type": "HVAC",
      "floor": 7,
      "room": 109,
      "installation_date": "5/5/2022",
      "manufacturer": "Manufacturer_2",
      "operational_time": 24260,
      "work_orders": 5,
      "repairs": 0,
      "last_serviced_date": "3/10/2023"
    },
    {
      "asset_id": 19,
      "asset_type": "Fire Alarm",
      "floor": 6,
      "room": 104,
      "installation_date": "8/25/2021",
      "manufacturer": "Manufacturer_5",
      "operational_time": 45428,
      "work_orders": 2,
      "repairs": 3,
      "last_serviced_date": "6/8/2023"
    },
    {
      "asset_id": 20,
      "asset_type": "Electrical Panel",
      "floor": 1,
      "room": 102,
      "installation_date": "3/26/2019",
      "manufacturer": "Manufacturer_2",
      "operational_time": 29859,
      "work_orders": 1,
      "repairs": 5,
      "last_serviced_date": "6/6/2023"
    },
    {
      "asset_id": 21,
      "asset_type": "Plumbing System",
      "floor": 10,
      "room": 102,
      "installation_date": "8/23/2022",
      "manufacturer": "Manufacturer_5",
      "operational_time": 5373,
      "work_orders": 5,
      "repairs": 0,
      "last_serviced_date": "12/19/2022"
    },
    {
      "asset_id": 22,
      "asset_type": "Fire Alarm",
      "floor": 9,
      "room": 102,
      "installation_date": "6/21/2023",
      "manufacturer": "Manufacturer_5",
      "operational_time": 2923,
      "work_orders": 8,
      "repairs": 3,
      "last_serviced_date": "7/20/2023"
    }
  ]
  